services:
  eos-storage:
    build:
      context: .
      dockerfile: Dockerfile.eos
    ulimits:
      nproc: 57875
      nofile: 1024000
      core: -1
    privileged: true
    healthcheck:
      test: eos file info /eos/user
      interval: 10s
      timeout: 5s
  revad:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    tmpfs:
      - /tmp:size=256m,mode=1777
    volumes:
      - ./revad:/etc/revad:ro
      - ./pki:/etc/pki:ro
    environment:
      - SSL_CERT_FILE=/etc/pki/ca.crt
    command: -c /etc/revad/cernbox.toml
    depends_on:
      eos-storage:
        condition: service_healthy
